# Generated by Django 4.1.1 on 2022-10-17 13:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(2, 'two seats'), (4, 'four seats'), (6, 'six seats'), (8, 'eight seats')])),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('preferred_payment_method', models.IntegerField(blank=True, choices=[(1, 'cash'), (2, 'credit card'), (3, 'check')], null=True)),
                ('people_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(14)])),
                ('seats', models.ManyToManyField(to='seats.seat')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
